name: recap_maker
description: Movie recap video editor for Myanmar creators.
publish_to: 'none'
version: 1.2.0+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^13.0.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  http: ^1.2.2
  video_player: ^2.9.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Padauk
      fonts:
        - asset: assets/fonts/Padauk-Regular.ttf
        - asset: assets/fonts/Padauk-Bold.ttf
          weight: 700
